# Generated by Django 5.2.1 on 2025-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
